import os
from pathlib import Path
from typing import Optional

from langchain.chat_models import ChatAnthropic
from langchain.schema import HumanMessage, SystemMessage

from .llm.simple_chat_chain import SimpleChat

from .sanity_check_spec import sanity_check_spec


def compile_spec(spec_path: str) -> None:
    """Compile a markdown specification file into Python code."""
    # First run the sanity check
    checked_spec = sanity_check_spec(spec_path)
    
    # Set up tlc directory
    spec_dir = Path(spec_path).parent
    tlc_dir = spec_dir / "tlc"
    tlc_dir.mkdir(exist_ok=True)
    
    # Create __init__.py if it doesn't exist
    init_path = tlc_dir / "__init__.py"
    if not init_path.exists():
        init_content = """# This file was generated by tlc, the package here is managed by AI and therefore
# might not be worth reading, it is generated by the specifications in the parent directory"""
        init_path.write_text(init_content)

    # System prompt for all interactions
    system_prompt = """You are a highly skilled Python software engineer. Your job is to read module specifications that describe the implementation of a Python module and turn it into clean, working code.

The specification files should generally define:
- Dependencies on other modules (named like [[path/to/module]])
- The interface this module exposes and how it is used
- the inputs and outputs of the program
- the command arguments of the program
- how the program is implemented

Sometimes specifications may include pseudo-code, intended to make it clear about how a bit of the program should be implemented."""

    chat = SimpleChat(
        system_prompt=system_prompt,
        model="claude-sonnet",
        debug_name=f"{checked_spec.module_name}.compile"
    )

    # Generate code
    code_prompt = f"""Consider the following specification:

====== BEGIN {checked_spec.module_name} specification ======
{checked_spec.no_context_spec}
====== END {checked_spec.module_name} specification ======

We have reviewed this specification, and discussed some clarifications in this Q&A:

{checked_spec.q_and_a}

The specification is ready to implement in {checked_spec.code_target_path}. Write the code for this module. Do not write anything else, just the code. Do not include the markdown back-ticks, we're going to output this straight to {checked_spec.code_target_path}."""
    
    code = chat.call(code_prompt)
    
    # Write the generated code
    with open(checked_spec.code_target_path, 'w') as f:
        f.write(code)

    # Review the code
    review_prompt = f"""Consider the following specification:

====== BEGIN {checked_spec.module_name} specification ======
{checked_spec.no_context_spec}
====== END {checked_spec.module_name} specification ======

Here is our implementation:

====== BEGIN {checked_spec.code_target_path} implementation ======
{code}
====== END {checked_spec.code_target_path} implementation ======

Review this implementation. Is it complete? Is it valid code? Does it meet our specifications expectations?"""

    review = chat.call(review_prompt)
    
    # Check if implementation is ready
    if review.lower().strip() == "yes":
        print("Compile succeeded")
    else:
        print(review)
