import os
import logging
from dataclasses import dataclass
from pathlib import Path
import jinja2

from .llm.langchain_logging import save_logs
from .specification_document import preprocess_spec_context, get_code_target
from .llm.simple_chat_chain import SimpleChat

@dataclass
class CheckedSpecification:
    module_name: str
    code_target_path: str
    no_context_spec: str
    q_and_a: str

def setup_logging(module_name: str, tlc_dir: Path):
    logger = logging.getLogger(module_name)
    logger.setLevel(logging.DEBUG)

    # Console handler
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(logging.Formatter('%(message)s'))
    logger.addHandler(console)

    # File handler
    log_dir = tlc_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_dir / f"{module_name}.log", encoding='utf-8')
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)

    return logger

def ensure_tlc_directory(spec_path: Path) -> Path:
    tlc_dir = spec_path.parent / "tlc"
    tlc_dir.mkdir(exist_ok=True)
    
    init_path = tlc_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# This file was generated by tlc, the package here is managed by AI and therefore\n"
                           "# might not be worth reading, it is generated by the specifications in the parent directory\n",
                           encoding='utf-8')
    
    return tlc_dir

def read_existing_qa(qa_path: Path) -> str:
    if qa_path.exists():
        return qa_path.read_text(encoding='utf-8')
    return ""

def sanity_check_spec(spec_path: str) -> CheckedSpecification | None:
    try:
        spec_path = Path(spec_path)
        module_name = spec_path.stem
        logger = setup_logging(module_name, ensure_tlc_directory(spec_path))
        
        logger.info(f"Processing specification: {spec_path}")
        
        # Preprocess spec
        no_context_spec = preprocess_spec_context(spec_path)
        no_context_path = spec_path.parent / "tlc" / f"{module_name}.no-context.md"
        no_context_path.write_text(no_context_spec, encoding='utf-8')
        logger.info(f"Wrote context-free spec to {no_context_path}")
        
        code_target = get_code_target(spec_path)
        if not code_target:
            logger.info("No code target found in specification")
            return None
        
        system_prompt = """You are a specification compiler. You take markdown documents describing the implementation of a single python module file and turn them into code.

The specification files should generally define:
- Dependencies on other modules (named like [[path/to/module]])
- The interface this module exposes and how it is used
- the inputs and outputs of the program
- the command arguments of the program
- how the program is implemented

Sometimes specifications may include pseudo-code, intended to make it clear about how a bit of the program should be implemented."""

        chat = SimpleChat(
            system_prompt=system_prompt,
            model="claude-sonnet",
            debug_name=f"{module_name}.sanity"
        )
        
        # Initial sanity check
        template = """Read the spec:

======= BEGIN {{module_name}} spec =======
{{spec}}
======== END {{module_name}} spec ========

Is it ambiguous? Are there problems that the spec doesn't address? Are there unanswered questions? Are there references to concepts that are not yet defined and understood?

Do not try to write the code yet. Just describe any weaknesses you see in the specification."""
        
        response = chat.call(template, module_name=module_name, spec=no_context_spec)
        logger.debug(f"Initial sanity check response: {response}")
        
        # Read existing Q&A
        qa_path = spec_path.parent / "tlc" / f"{module_name}.questions.md"
        existing_qa = read_existing_qa(qa_path)
        
        # Check implementation viability
        template = """{% if q_and_a %}
Here is a Q&A from our last review of this document:

{q_and_a}{% endif %}

Do we have enough information to implement this specification in code? Does this implementation make sense? Will it work? Why not?

We are allowed to make reasonable assumptions, but we must explain them.

Do not try to write the code yet. Just explain why this will work or not."""
        
        explanation = chat.call(template, q_and_a=existing_qa)
        logger.debug(f"Implementation viability response: {explanation}")
        
        # Should we build?
        build_failed = chat.call("In summary, should we build this, or do we need to improve the spec? Just answer yes or no, nothing else.").lower() == "no"
        
        if build_failed:
            print("Sanity check failed. The specification needs improvement.")
        
        # Check for questions
        has_questions = chat.call("Are there unanswered questions? Just answer yes or no, nothing else.").lower() == "yes"
        
        if has_questions:
            template = """List all the unanswered questions or clarifications, and besides each one, write your best assumption on the answer.

Do not number the questions, just list them like this:

**Question**: {question}
  **Assumption**: {assumption}

If there is an **Answer** from the last review, you must keep it the same.

If there is no reasonable way to answer the question, do not make an assumption, just state that you don't know. If you're unsure about a particular assumption, say so."""
            
            qa_response = chat.call(template)
            qa_path.write_text(qa_response, encoding='utf-8')
            logger.info(f"Wrote Q&A to {qa_path}")
            
            if build_failed:
                critical_questions = chat.call("Which questions are critical to answer in order to build this module?")
                print(critical_questions)
        
        return CheckedSpecification(
            module_name=module_name,
            code_target_path=code_target,
            no_context_spec=no_context_spec,
            q_and_a=existing_qa
        )
        
    finally:
        save_logs()

def main():
    try:
        import sys
        if len(sys.argv) != 2:
            print("Usage: sanity-check-spec module-name.md")
            sys.exit(1)
        
        sanity_check_spec(sys.argv[1])
        
    finally:
        save_logs()

if __name__ == "__main__":
    main()