[project]
name = "tlc"
version = "0.1.0"
description = "AI Generated Python Modules"
dependencies = [
    "jinja2>=3.1.6",
    "langchain>=0.3.20",
    "langchain-anthropic>=0.3.9",
]

[project.scripts]
tlc = "tlc.the_last_compiler:main" 
